//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2013.04.12 at 11:58:52 AM EDT
//
package ietf.params.xml.ns.vcard.property;

import java.util.Objects;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;

/**
 * Java class for AdrPropertyType complex type.
 * <p/>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * <p/>
 * <
 * pre> &lt;complexType name="AdrPropertyType"> &lt;complexContent>
 * &lt;extension base="{urn:ietf:params:xml:ns:vcard-4.0}BasePropertyType">
 * &lt;sequence> &lt;element name="pobox"
 * type="{urn:ietf:params:xml:ns:vcard-4.0}TextListPropertyType" minOccurs="0"/>
 * &lt;element name="ext"
 * type="{urn:ietf:params:xml:ns:vcard-4.0}TextListPropertyType" minOccurs="0"/>
 * &lt;element name="street"
 * type="{urn:ietf:params:xml:ns:vcard-4.0}TextListPropertyType" minOccurs="0"/>
 * &lt;element name="locality"
 * type="{urn:ietf:params:xml:ns:vcard-4.0}TextListPropertyType" minOccurs="0"/>
 * &lt;element name="region"
 * type="{urn:ietf:params:xml:ns:vcard-4.0}TextListPropertyType" minOccurs="0"/>
 * &lt;element name="code"
 * type="{urn:ietf:params:xml:ns:vcard-4.0}TextListPropertyType" minOccurs="0"/>
 * &lt;element name="country"
 * type="{urn:ietf:params:xml:ns:vcard-4.0}TextListPropertyType" minOccurs="0"/>
 * &lt;/sequence> &lt;/extension> &lt;/complexContent> &lt;/complexType>
 * </pre>
 * <p/>
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AdrPropertyType", propOrder = {
  "pobox",
  "ext",
  "street",
  "locality",
  "region",
  "code",
  "country"
})
public class AdrPropertyType extends BasePropertyType {

  protected TextListPropertyType pobox;
  protected TextListPropertyType ext;
  protected TextListPropertyType street;
  protected TextListPropertyType locality;
  protected TextListPropertyType region;
  protected TextListPropertyType code;
  protected TextListPropertyType country;

  /**
   * Gets the value of the pobox property.
   * <p/>
   * @return possible object is {@link TextListPropertyType }
   *
   */
  public String getPobox() {
    return pobox != null ? pobox.getEntry() : null;
  }

  /**
   * Sets the value of the pobox property.
   * <p/>
   * @param value allowed object is {@link TextListPropertyType }
   *
   */
  public void setPobox(String value) {
    this.pobox = new TextListPropertyType(value);
  }

  /**
   * Gets the value of the ext property.
   * <p/>
   * @return possible object is {@link TextListPropertyType }
   *
   */
  public String getExt() {
    return ext != null ? ext.getEntry() : null;
  }

  /**
   * Sets the value of the ext property.
   * <p/>
   * @param value allowed object is {@link TextListPropertyType }
   *
   */
  public void setExt(String value) {
    this.ext = new TextListPropertyType(value);
  }

  public boolean isSetExt() {
    return (this.ext != null);
  }

  /**
   * Gets the value of the street property.
   * <p/>
   * @return possible object is {@link TextListPropertyType }
   *
   */
  public String getStreet() {
    return street != null ? street.getEntry() : null;
  }

  /**
   * Sets the value of the street property.
   * <p/>
   * @param value allowed object is {@link TextListPropertyType }
   *
   */
  public void setStreet(String value) {
    this.street = new TextListPropertyType(value);
  }

  public boolean isSetStreet() {
    return (this.street != null);
  }

  /**
   * Gets the value of the locality property. This is the US CITY.
   * <p/>
   * @return possible object is {@link TextListPropertyType }
   *
   */
  public String getLocality() {
    return locality != null ? locality.getEntry() : null;
  }

  /**
   * Sets the value of the locality property. This is the US CITY property.
   * <p/>
   * @param value allowed object is {@link TextListPropertyType }
   *
   */
  public void setLocality(String value) {
    this.locality = new TextListPropertyType(value);
  }

  public boolean isSetLocality() {
    return (this.locality != null);
  }

  /**
   * Gets the value of the region property. This is the US STATE property.
   * <p/>
   * @return possible object is {@link TextListPropertyType }
   *
   */
  public String getRegion() {
    return region != null ? region.getEntry() : null;
  }

  /**
   * Sets the value of the region property.
   * <p/>
   * @param value allowed object is {@link TextListPropertyType }
   *
   */
  public void setRegion(String value) {
    this.region = new TextListPropertyType(value);
  }

  public boolean isSetRegion() {
    return (this.region != null);
  }

  /**
   * Gets the value of the code property. This is the US ZIP property.
   * <p/>
   * @return possible object is {@link TextListPropertyType }
   *
   */
  public String getCode() {
    return code != null ? code.getEntry() : null;
  }

  /**
   * Sets the value of the code property.
   * <p/>
   * @param value allowed object is {@link TextListPropertyType }
   *
   */
  public void setCode(String value) {
    this.code = new TextListPropertyType(value);
  }

  public boolean isSetCode() {
    return (this.code != null);
  }

  /**
   * Gets the value of the country property.
   * <p/>
   * @return possible object is {@link TextListPropertyType }
   *
   */
  public String getCountry() {
    return country != null ? country.getEntry() : null;
  }

  /**
   * Sets the value of the country property.
   * <p/>
   * @param value allowed object is {@link TextListPropertyType }
   *
   */
  public void setCountry(String value) {
    this.country = new TextListPropertyType(value);
  }

  public boolean isSetCountry() {
    return (this.country != null);
  }

  @Override
  public int hashCode() {
    int hash = 3;
    hash = 53 * hash + Objects.hashCode(this.pobox);
    hash = 53 * hash + Objects.hashCode(this.ext);
    hash = 53 * hash + Objects.hashCode(this.street);
    hash = 53 * hash + Objects.hashCode(this.locality);
    hash = 53 * hash + Objects.hashCode(this.region);
    hash = 53 * hash + Objects.hashCode(this.code);
    hash = 53 * hash + Objects.hashCode(this.country);
    return hash;
  }

  @Override
  public boolean equals(Object obj) {
    if (obj == null) {
      return false;
    }
    if (getClass() != obj.getClass()) {
      return false;
    }
    final AdrPropertyType other = (AdrPropertyType) obj;
    if (this.hashCode() != obj.hashCode()) {
      return false;
    }
    return true;
  }

  @Override
  public String toString() {
    return "AdrPropertyType"
      + " pobox [" + getPobox()
      + "] ext [" + getExt()
      + "] street [" + getStreet()
      + "] locality [" + getLocality()
      + "] region [" + getRegion()
      + "] code [" + getCode()
      + "] country [" + getCountry()
      + '}';
  }
}
