//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2013.04.12 at 11:58:52 AM EDT
//
package ietf.params.xml.ns.vcard.property;

import ietf.params.xml.ns.vcard.DateAndOrTimeType;
import java.util.Objects;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * Java class for BdayPropertyType complex type.
 * <p/>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * <p/>
 * <
 * pre> &lt;complexType name="BdayPropertyType"> &lt;complexContent>
 * &lt;extension base="{urn:ietf:params:xml:ns:vcard-4.0}BasePropertyType">
 * &lt;sequence> &lt;choice> &lt;element
 * ref="{urn:ietf:params:xml:ns:vcard-4.0}date-and-or-time"/> &lt;element
 * ref="{urn:ietf:params:xml:ns:vcard-4.0}text"/> &lt;/choice> &lt;/sequence>
 * &lt;/extension> &lt;/complexContent> &lt;/complexType>
 * </pre>
 * <p/>
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BdayPropertyType", propOrder = {
  "dateAndOrTime",
  "text"
})
public class BdayPropertyType extends BasePropertyType {

  @XmlElement(name = "date-and-or-time")
  protected DateAndOrTimeType dateAndOrTime;
  protected String text;

  /**
   * Gets the value of the dateAndOrTime property.
   * <p/>
   * @return possible object is {@link DateAndOrTimeType }
   *
   */
  public DateAndOrTimeType getDateAndOrTime() {
    return dateAndOrTime;
  }

  /**
   * Sets the value of the dateAndOrTime property.
   * <p/>
   * @param value allowed object is {@link DateAndOrTimeType }
   *
   */
  public void setDateAndOrTime(DateAndOrTimeType value) {
    this.dateAndOrTime = value;
  }

  public boolean isSetDateAndOrTime() {
    return (this.dateAndOrTime != null);
  }

  /**
   * Gets the value of the text property.
   * <p/>
   * @return possible object is {@link String }
   *
   */
  public String getText() {
    return text;
  }

  /**
   * Sets the value of the text property.
   * <p/>
   * @param value allowed object is {@link String }
   *
   */
  public void setText(String value) {
    this.text = value;
  }

  public boolean isSetText() {
    return (this.text != null);
  }

  @Override
  public int hashCode() {
    int hash = 5;
    hash = 67 * hash + Objects.hashCode(this.dateAndOrTime);
    hash = 67 * hash + Objects.hashCode(this.text);
    return hash;
  }

  @Override
  public boolean equals(Object obj) {
    if (obj == null) {
      return false;
    }
    if (getClass() != obj.getClass()) {
      return false;
    }
    final BdayPropertyType other = (BdayPropertyType) obj;
    if (!Objects.equals(this.dateAndOrTime, other.dateAndOrTime)) {
      return false;
    }
    if (!Objects.equals(this.text, other.text)) {
      return false;
    }
    return true;
  }

  @Override
  public String toString() {
    return "BdayPropertyType{" + "dateAndOrTime=" + dateAndOrTime + ", text=" + text + '}';
  }
}
