//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2013.04.12 at 11:58:52 AM EDT
//
package ietf.params.xml.ns.vcard;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;

/**
 * Java class for ArrayOfVcards complex type.
 * <p/>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * <p/>
 * <
 * pre> &lt;complexType name="ArrayOfVcards"> &lt;complexContent>
 * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 * &lt;sequence> &lt;element ref="{urn:ietf:params:xml:ns:vcard-4.0}vcard"
 * maxOccurs="unbounded" minOccurs="0"/> &lt;/sequence> &lt;/restriction>
 * &lt;/complexContent> &lt;/complexType>
 * </pre>
 * <p/>
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ArrayOfVcards", propOrder = {
  "vcard"
})
public class ArrayOfVcards {

  protected List<VCard> vcard;

  /**
   * Gets the value of the vcard property.
   * <p/>
   * This accessor method returns a reference to the live list, not a snapshot.
   * Therefore any modification you make to the returned list will be present
   * inside the JAXB object. This is why there is not a
   * <CODE>set</CODE> method for the vcard property.
   * <p/>
   * For example, to add a new item, do as follows:
   * <pre>
   *    getVcard().add(newItem);
   * </pre>
   * <p/>
   *
   * Objects of the following type(s) are allowed in the list {@link VCard }
   *
   *
   */
  public List<VCard> getVcard() {
    if (vcard == null) {
      vcard = new ArrayList<VCard>();
    }
    return this.vcard;
  }

  public boolean isSetVcard() {
    return ((this.vcard != null) && (!this.vcard.isEmpty()));
  }

  public void unsetVcard() {
    this.vcard = null;
  }

  @Override
  public int hashCode() {
    int hash = 5;
    hash = 53 * hash + Objects.hashCode(this.vcard);
    return hash;
  }

  @Override
  public boolean equals(Object obj) {
    if (obj == null) {
      return false;
    }
    if (getClass() != obj.getClass()) {
      return false;
    }
    final ArrayOfVcards other = (ArrayOfVcards) obj;
    if (!Objects.equals(this.vcard, other.vcard)) {
      return false;
    }
    return true;
  }
}
