//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2013.04.12 at 11:58:52 AM EDT
//
package ietf.params.xml.ns.vcard;

import java.util.Objects;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * Java class for DateAndOrTimeType complex type.
 * <p/>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * <p/>
 * <
 * pre>
 * &lt;complexType name="DateAndOrTimeType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;choice>
 *           &lt;element ref="{urn:ietf:params:xml:ns:vcard-4.0}date"/>
 *           &lt;element ref="{urn:ietf:params:xml:ns:vcard-4.0}date-time"/>
 *           &lt;element ref="{urn:ietf:params:xml:ns:vcard-4.0}time"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * <p/>
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DateAndOrTimeType", propOrder = {
  "date",
  "dateTime",
  "time"
})
public class DateAndOrTimeType {

  protected String date;
  @XmlElement(name = "date-time")
  protected String dateTime;
  protected String time;

  /**
   * Gets the value of the date property.
   * <p/>
   * @return possible object is {@link String }
   *
   */
  public String getDate() {
    return date;
  }

  /**
   * Sets the value of the date property.
   * <p/>
   * @param value allowed object is {@link String }
   *
   */
  public void setDate(String value) {
    this.date = value;
  }

  public boolean isSetDate() {
    return (this.date != null);
  }

  /**
   * Gets the value of the dateTime property.
   * <p/>
   * @return possible object is {@link String }
   *
   */
  public String getDateTime() {
    return dateTime;
  }

  /**
   * Sets the value of the dateTime property.
   * <p/>
   * @param value allowed object is {@link String }
   *
   */
  public void setDateTime(String value) {
    this.dateTime = value;
  }

  public boolean isSetDateTime() {
    return (this.dateTime != null);
  }

  /**
   * Gets the value of the time property.
   * <p/>
   * @return possible object is {@link String }
   *
   */
  public String getTime() {
    return time;
  }

  /**
   * Sets the value of the time property.
   * <p/>
   * @param value allowed object is {@link String }
   *
   */
  public void setTime(String value) {
    this.time = value;
  }

  @Override
  public int hashCode() {
    int hash = 5;
    hash = 31 * hash + Objects.hashCode(this.date);
    hash = 31 * hash + Objects.hashCode(this.dateTime);
    hash = 31 * hash + Objects.hashCode(this.time);
    return hash;
  }

  @Override
  public boolean equals(Object obj) {
    if (obj == null) {
      return false;
    }
    if (getClass() != obj.getClass()) {
      return false;
    }
    final DateAndOrTimeType other = (DateAndOrTimeType) obj;
    if (!Objects.equals(this.date, other.date)) {
      return false;
    }
    if (!Objects.equals(this.dateTime, other.dateTime)) {
      return false;
    }
    if (!Objects.equals(this.time, other.time)) {
      return false;
    }
    return true;
  }

  public boolean isSetTime() {
    return (this.time != null);
  }
}
