//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2013.04.12 at 11:58:52 AM EDT
//
package ietf.params.xml.ns.vcard.parameter;

import java.util.Objects;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * Java class for LanguageParamType complex type.
 * <p/>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * <p/>
 * <
 * pre> &lt;complexType name="LanguageParamType"> &lt;complexContent>
 * &lt;extension base="{urn:ietf:params:xml:ns:vcard-4.0}BaseParameterType">
 * &lt;sequence> &lt;element
 * ref="{urn:ietf:params:xml:ns:vcard-4.0}language-tag"/> &lt;/sequence>
 * &lt;/extension> &lt;/complexContent> &lt;/complexType>
 * </pre>
 * <p/>
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "LanguageParamType", propOrder = {
  "languageTag"
})
public class LanguageParamType extends BaseParameterType {

  @XmlElement(name = "language-tag", required = true)
  protected String languageTag;

  /**
   * Gets the value of the languageTag property.
   * <p/>
   * @return possible object is {@link String }
   *
   */
  public String getLanguageTag() {
    return languageTag;
  }

  /**
   * Sets the value of the languageTag property.
   * <p/>
   * @param value allowed object is {@link String }
   *
   */
  public void setLanguageTag(String value) {
    this.languageTag = value;
  }

  public boolean isSetLanguageTag() {
    return (this.languageTag != null);
  }

  @Override
  public int hashCode() {
    int hash = 7;
    hash = 67 * hash + Objects.hashCode(this.languageTag);
    return hash;
  }

  @Override
  public boolean equals(Object obj) {
    if (obj == null) {
      return false;
    }
    if (getClass() != obj.getClass()) {
      return false;
    }
    final LanguageParamType other = (LanguageParamType) obj;
    if (!Objects.equals(this.languageTag, other.languageTag)) {
      return false;
    }
    return true;
  }

  @Override
  public String toString() {
    return "LanguageParamType{" + "languageTag=" + languageTag + '}';
  }
}
