//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2013.04.12 at 11:58:52 AM EDT
//
package ietf.params.xml.ns.vcard.parameter;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * Java class for PidParamType complex type.
 * <p/>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * <p/>
 * <
 * pre> &lt;complexType name="PidParamType"> &lt;complexContent> &lt;extension
 * base="{urn:ietf:params:xml:ns:vcard-4.0}BaseParameterType"> &lt;sequence>
 * &lt;element ref="{urn:ietf:params:xml:ns:vcard-4.0}pid-val"
 * maxOccurs="unbounded"/> &lt;/sequence> &lt;/extension> &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * <p/>
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PidParamType", propOrder = {
  "pidVal"
})
public class PidParamType extends BaseParameterType {

  @XmlElement(name = "pid-val", required = true)
  protected List<String> pidVal;

  /**
   * Gets the value of the pidVal property.
   * <p/>
   * This accessor method returns a reference to the live list, not a snapshot.
   * Therefore any modification you make to the returned list will be present
   * inside the JAXB object. This is why there is not a
   * <CODE>set</CODE> method for the pidVal property.
   * <p/>
   * For example, to add a new item, do as follows:
   * <pre>
   *    getPidVal().add(newItem);
   * </pre>
   * <p/>
   *
   * Objects of the following type(s) are allowed in the list {@link String }
   *
   *
   */
  public List<String> getPidVal() {
    if (pidVal == null) {
      pidVal = new ArrayList<String>();
    }
    return this.pidVal;
  }

  public boolean isSetPidVal() {
    return ((this.pidVal != null) && (!this.pidVal.isEmpty()));
  }

  public void unsetPidVal() {
    this.pidVal = null;
  }

  @Override
  public int hashCode() {
    int hash = 5;
    hash = 17 * hash + Objects.hashCode(this.pidVal);
    return hash;
  }

  @Override
  public boolean equals(Object obj) {
    if (obj == null) {
      return false;
    }
    if (getClass() != obj.getClass()) {
      return false;
    }
    final PidParamType other = (PidParamType) obj;
    if (!Objects.equals(this.pidVal, other.pidVal)) {
      return false;
    }
    return true;
  }

  @Override
  public String toString() {
    return "PidParamType{" + "pidVal=" + pidVal + '}';
  }
}
