//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.09.19 at 12:48:54 PM EDT 
//


package ietf.params.xml.ns.vcard_4;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AdrPropertyType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AdrPropertyType">
 *   &lt;complexContent>
 *     &lt;extension base="{urn:ietf:params:xml:ns:vcard-4.0}BasePropertyType">
 *       &lt;sequence>
 *         &lt;element name="pobox" type="{urn:ietf:params:xml:ns:vcard-4.0}TextListPropertyType" minOccurs="0"/>
 *         &lt;element name="ext" type="{urn:ietf:params:xml:ns:vcard-4.0}TextListPropertyType" minOccurs="0"/>
 *         &lt;element name="street" type="{urn:ietf:params:xml:ns:vcard-4.0}TextListPropertyType" minOccurs="0"/>
 *         &lt;element name="locality" type="{urn:ietf:params:xml:ns:vcard-4.0}TextListPropertyType" minOccurs="0"/>
 *         &lt;element name="region" type="{urn:ietf:params:xml:ns:vcard-4.0}TextListPropertyType" minOccurs="0"/>
 *         &lt;element name="code" type="{urn:ietf:params:xml:ns:vcard-4.0}TextListPropertyType" minOccurs="0"/>
 *         &lt;element name="country" type="{urn:ietf:params:xml:ns:vcard-4.0}TextListPropertyType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AdrPropertyType", propOrder = {
    "pobox",
    "ext",
    "street",
    "locality",
    "region",
    "code",
    "country"
})
public class AdrPropertyType
    extends BasePropertyType
{

    protected TextListPropertyType pobox;
    protected TextListPropertyType ext;
    protected TextListPropertyType street;
    protected TextListPropertyType locality;
    protected TextListPropertyType region;
    protected TextListPropertyType code;
    protected TextListPropertyType country;

    /**
     * Gets the value of the pobox property.
     * 
     * @return
     *     possible object is
     *     {@link TextListPropertyType }
     *     
     */
    public TextListPropertyType getPobox() {
        return pobox;
    }

    /**
     * Sets the value of the pobox property.
     * 
     * @param value
     *     allowed object is
     *     {@link TextListPropertyType }
     *     
     */
    public void setPobox(TextListPropertyType value) {
        this.pobox = value;
    }

    /**
     * Gets the value of the ext property.
     * 
     * @return
     *     possible object is
     *     {@link TextListPropertyType }
     *     
     */
    public TextListPropertyType getExt() {
        return ext;
    }

    /**
     * Sets the value of the ext property.
     * 
     * @param value
     *     allowed object is
     *     {@link TextListPropertyType }
     *     
     */
    public void setExt(TextListPropertyType value) {
        this.ext = value;
    }

    /**
     * Gets the value of the street property.
     * 
     * @return
     *     possible object is
     *     {@link TextListPropertyType }
     *     
     */
    public TextListPropertyType getStreet() {
        return street;
    }

    /**
     * Sets the value of the street property.
     * 
     * @param value
     *     allowed object is
     *     {@link TextListPropertyType }
     *     
     */
    public void setStreet(TextListPropertyType value) {
        this.street = value;
    }

    /**
     * Gets the value of the locality property.
     * 
     * @return
     *     possible object is
     *     {@link TextListPropertyType }
     *     
     */
    public TextListPropertyType getLocality() {
        return locality;
    }

    /**
     * Sets the value of the locality property.
     * 
     * @param value
     *     allowed object is
     *     {@link TextListPropertyType }
     *     
     */
    public void setLocality(TextListPropertyType value) {
        this.locality = value;
    }

    /**
     * Gets the value of the region property.
     * 
     * @return
     *     possible object is
     *     {@link TextListPropertyType }
     *     
     */
    public TextListPropertyType getRegion() {
        return region;
    }

    /**
     * Sets the value of the region property.
     * 
     * @param value
     *     allowed object is
     *     {@link TextListPropertyType }
     *     
     */
    public void setRegion(TextListPropertyType value) {
        this.region = value;
    }

    /**
     * Gets the value of the code property.
     * 
     * @return
     *     possible object is
     *     {@link TextListPropertyType }
     *     
     */
    public TextListPropertyType getCode() {
        return code;
    }

    /**
     * Sets the value of the code property.
     * 
     * @param value
     *     allowed object is
     *     {@link TextListPropertyType }
     *     
     */
    public void setCode(TextListPropertyType value) {
        this.code = value;
    }

    /**
     * Gets the value of the country property.
     * 
     * @return
     *     possible object is
     *     {@link TextListPropertyType }
     *     
     */
    public TextListPropertyType getCountry() {
        return country;
    }

    /**
     * Sets the value of the country property.
     * 
     * @param value
     *     allowed object is
     *     {@link TextListPropertyType }
     *     
     */
    public void setCountry(TextListPropertyType value) {
        this.country = value;
    }

}
