//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.09.19 at 12:48:54 PM EDT 
//


package ietf.params.xml.ns.vcard_4;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for NamePropertyType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="NamePropertyType">
 *   &lt;complexContent>
 *     &lt;extension base="{urn:ietf:params:xml:ns:vcard-4.0}BasePropertyType">
 *       &lt;sequence>
 *         &lt;element name="surname" type="{urn:ietf:params:xml:ns:vcard-4.0}TextListPropertyType" minOccurs="0"/>
 *         &lt;element name="given" type="{urn:ietf:params:xml:ns:vcard-4.0}TextListPropertyType" minOccurs="0"/>
 *         &lt;element name="additional" type="{urn:ietf:params:xml:ns:vcard-4.0}TextListPropertyType" minOccurs="0"/>
 *         &lt;element name="prefix" type="{urn:ietf:params:xml:ns:vcard-4.0}TextListPropertyType" minOccurs="0"/>
 *         &lt;element name="suffix" type="{urn:ietf:params:xml:ns:vcard-4.0}TextListPropertyType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "NamePropertyType", propOrder = {
    "surname",
    "given",
    "additional",
    "prefix",
    "suffix"
})
public class NamePropertyType
    extends BasePropertyType
{

    protected TextListPropertyType surname;
    protected TextListPropertyType given;
    protected TextListPropertyType additional;
    protected TextListPropertyType prefix;
    protected TextListPropertyType suffix;

    /**
     * Gets the value of the surname property.
     * 
     * @return
     *     possible object is
     *     {@link TextListPropertyType }
     *     
     */
    public TextListPropertyType getSurname() {
        return surname;
    }

    /**
     * Sets the value of the surname property.
     * 
     * @param value
     *     allowed object is
     *     {@link TextListPropertyType }
     *     
     */
    public void setSurname(TextListPropertyType value) {
        this.surname = value;
    }

    /**
     * Gets the value of the given property.
     * 
     * @return
     *     possible object is
     *     {@link TextListPropertyType }
     *     
     */
    public TextListPropertyType getGiven() {
        return given;
    }

    /**
     * Sets the value of the given property.
     * 
     * @param value
     *     allowed object is
     *     {@link TextListPropertyType }
     *     
     */
    public void setGiven(TextListPropertyType value) {
        this.given = value;
    }

    /**
     * Gets the value of the additional property.
     * 
     * @return
     *     possible object is
     *     {@link TextListPropertyType }
     *     
     */
    public TextListPropertyType getAdditional() {
        return additional;
    }

    /**
     * Sets the value of the additional property.
     * 
     * @param value
     *     allowed object is
     *     {@link TextListPropertyType }
     *     
     */
    public void setAdditional(TextListPropertyType value) {
        this.additional = value;
    }

    /**
     * Gets the value of the prefix property.
     * 
     * @return
     *     possible object is
     *     {@link TextListPropertyType }
     *     
     */
    public TextListPropertyType getPrefix() {
        return prefix;
    }

    /**
     * Sets the value of the prefix property.
     * 
     * @param value
     *     allowed object is
     *     {@link TextListPropertyType }
     *     
     */
    public void setPrefix(TextListPropertyType value) {
        this.prefix = value;
    }

    /**
     * Gets the value of the suffix property.
     * 
     * @return
     *     possible object is
     *     {@link TextListPropertyType }
     *     
     */
    public TextListPropertyType getSuffix() {
        return suffix;
    }

    /**
     * Sets the value of the suffix property.
     * 
     * @param value
     *     allowed object is
     *     {@link TextListPropertyType }
     *     
     */
    public void setSuffix(TextListPropertyType value) {
        this.suffix = value;
    }

}
