//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.09.19 at 12:48:54 PM EDT 
//


package ietf.params.xml.ns.vcard_4;

import java.math.BigInteger;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the ietf.params.xml.ns.vcard_4 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Pref_QNAME = new QName("urn:ietf:params:xml:ns:vcard-4.0", "pref");
    private final static QName _Language_QNAME = new QName("urn:ietf:params:xml:ns:vcard-4.0", "language");
    private final static QName _Caladruri_QNAME = new QName("urn:ietf:params:xml:ns:vcard-4.0", "caladruri");
    private final static QName _Sound_QNAME = new QName("urn:ietf:params:xml:ns:vcard-4.0", "sound");
    private final static QName _Email_QNAME = new QName("urn:ietf:params:xml:ns:vcard-4.0", "email");
    private final static QName _DateAndOrTime_QNAME = new QName("urn:ietf:params:xml:ns:vcard-4.0", "date-and-or-time");
    private final static QName _Clientpidmap_QNAME = new QName("urn:ietf:params:xml:ns:vcard-4.0", "clientpidmap");
    private final static QName _Url_QNAME = new QName("urn:ietf:params:xml:ns:vcard-4.0", "url");
    private final static QName _Uri_QNAME = new QName("urn:ietf:params:xml:ns:vcard-4.0", "uri");
    private final static QName _Label_QNAME = new QName("urn:ietf:params:xml:ns:vcard-4.0", "label");
    private final static QName _Nickname_QNAME = new QName("urn:ietf:params:xml:ns:vcard-4.0", "nickname");
    private final static QName _LanguageTag_QNAME = new QName("urn:ietf:params:xml:ns:vcard-4.0", "language-tag");
    private final static QName _Text_QNAME = new QName("urn:ietf:params:xml:ns:vcard-4.0", "text");
    private final static QName _Geo_QNAME = new QName("urn:ietf:params:xml:ns:vcard-4.0", "geo");
    private final static QName _Key_QNAME = new QName("urn:ietf:params:xml:ns:vcard-4.0", "key");
    private final static QName _Fn_QNAME = new QName("urn:ietf:params:xml:ns:vcard-4.0", "fn");
    private final static QName _Boolean_QNAME = new QName("urn:ietf:params:xml:ns:vcard-4.0", "boolean");
    private final static QName _Role_QNAME = new QName("urn:ietf:params:xml:ns:vcard-4.0", "role");
    private final static QName _Gender_QNAME = new QName("urn:ietf:params:xml:ns:vcard-4.0", "gender");
    private final static QName _Caluri_QNAME = new QName("urn:ietf:params:xml:ns:vcard-4.0", "caluri");
    private final static QName _Time_QNAME = new QName("urn:ietf:params:xml:ns:vcard-4.0", "time");
    private final static QName _Fburl_QNAME = new QName("urn:ietf:params:xml:ns:vcard-4.0", "fburl");
    private final static QName _Related_QNAME = new QName("urn:ietf:params:xml:ns:vcard-4.0", "related");
    private final static QName _Type_QNAME = new QName("urn:ietf:params:xml:ns:vcard-4.0", "type");
    private final static QName _Float_QNAME = new QName("urn:ietf:params:xml:ns:vcard-4.0", "float");
    private final static QName _Prodid_QNAME = new QName("urn:ietf:params:xml:ns:vcard-4.0", "prodid");
    private final static QName _Tel_QNAME = new QName("urn:ietf:params:xml:ns:vcard-4.0", "tel");
    private final static QName _BaseProperty_QNAME = new QName("urn:ietf:params:xml:ns:vcard-4.0", "baseProperty");
    private final static QName _Geoloc_QNAME = new QName("urn:ietf:params:xml:ns:vcard-4.0", "geoloc");
    private final static QName _Uid_QNAME = new QName("urn:ietf:params:xml:ns:vcard-4.0", "uid");
    private final static QName _Tzid_QNAME = new QName("urn:ietf:params:xml:ns:vcard-4.0", "tzid");
    private final static QName _BaseParameter_QNAME = new QName("urn:ietf:params:xml:ns:vcard-4.0", "baseParameter");
    private final static QName _Categories_QNAME = new QName("urn:ietf:params:xml:ns:vcard-4.0", "categories");
    private final static QName _Source_QNAME = new QName("urn:ietf:params:xml:ns:vcard-4.0", "source");
    private final static QName _Altid_QNAME = new QName("urn:ietf:params:xml:ns:vcard-4.0", "altid");
    private final static QName _SortAs_QNAME = new QName("urn:ietf:params:xml:ns:vcard-4.0", "sort-as");
    private final static QName _Tz_QNAME = new QName("urn:ietf:params:xml:ns:vcard-4.0", "tz");
    private final static QName _Vcards_QNAME = new QName("urn:ietf:params:xml:ns:vcard-4.0", "vcards");
    private final static QName _Vcard_QNAME = new QName("urn:ietf:params:xml:ns:vcard-4.0", "vcard");
    private final static QName _Photo_QNAME = new QName("urn:ietf:params:xml:ns:vcard-4.0", "photo");
    private final static QName _Pid_QNAME = new QName("urn:ietf:params:xml:ns:vcard-4.0", "pid");
    private final static QName _N_QNAME = new QName("urn:ietf:params:xml:ns:vcard-4.0", "n");
    private final static QName _Integer_QNAME = new QName("urn:ietf:params:xml:ns:vcard-4.0", "integer");
    private final static QName _Anniversary_QNAME = new QName("urn:ietf:params:xml:ns:vcard-4.0", "anniversary");
    private final static QName _Impp_QNAME = new QName("urn:ietf:params:xml:ns:vcard-4.0", "impp");
    private final static QName _Member_QNAME = new QName("urn:ietf:params:xml:ns:vcard-4.0", "member");
    private final static QName _Logo_QNAME = new QName("urn:ietf:params:xml:ns:vcard-4.0", "logo");
    private final static QName _Note_QNAME = new QName("urn:ietf:params:xml:ns:vcard-4.0", "note");
    private final static QName _PidVal_QNAME = new QName("urn:ietf:params:xml:ns:vcard-4.0", "pid-val");
    private final static QName _Title_QNAME = new QName("urn:ietf:params:xml:ns:vcard-4.0", "title");
    private final static QName _Bday_QNAME = new QName("urn:ietf:params:xml:ns:vcard-4.0", "bday");
    private final static QName _Timestamp_QNAME = new QName("urn:ietf:params:xml:ns:vcard-4.0", "timestamp");
    private final static QName _Kind_QNAME = new QName("urn:ietf:params:xml:ns:vcard-4.0", "kind");
    private final static QName _Date_QNAME = new QName("urn:ietf:params:xml:ns:vcard-4.0", "date");
    private final static QName _Org_QNAME = new QName("urn:ietf:params:xml:ns:vcard-4.0", "org");
    private final static QName _Calscale_QNAME = new QName("urn:ietf:params:xml:ns:vcard-4.0", "calscale");
    private final static QName _Lang_QNAME = new QName("urn:ietf:params:xml:ns:vcard-4.0", "lang");
    private final static QName _DateTime_QNAME = new QName("urn:ietf:params:xml:ns:vcard-4.0", "date-time");
    private final static QName _Rev_QNAME = new QName("urn:ietf:params:xml:ns:vcard-4.0", "rev");
    private final static QName _Adr_QNAME = new QName("urn:ietf:params:xml:ns:vcard-4.0", "adr");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: ietf.params.xml.ns.vcard_4
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link UriPropertyType }
     * 
     */
    public UriPropertyType createUriPropertyType() {
        return new UriPropertyType();
    }

    /**
     * Create an instance of {@link UriParamType }
     * 
     */
    public UriParamType createUriParamType() {
        return new UriParamType();
    }

    /**
     * Create an instance of {@link TextUriPropertyType }
     * 
     */
    public TextUriPropertyType createTextUriPropertyType() {
        return new TextUriPropertyType();
    }

    /**
     * Create an instance of {@link TextPropertyType }
     * 
     */
    public TextPropertyType createTextPropertyType() {
        return new TextPropertyType();
    }

    /**
     * Create an instance of {@link TextParamType }
     * 
     */
    public TextParamType createTextParamType() {
        return new TextParamType();
    }

    /**
     * Create an instance of {@link TextListPropertyType }
     * 
     */
    public TextListPropertyType createTextListPropertyType() {
        return new TextListPropertyType();
    }

    /**
     * Create an instance of {@link ClientPidmapPropertyType }
     * 
     */
    public ClientPidmapPropertyType createClientPidmapPropertyType() {
        return new ClientPidmapPropertyType();
    }

    /**
     * Create an instance of {@link DateAndOrTimeType }
     * 
     */
    public DateAndOrTimeType createDateAndOrTimeType() {
        return new DateAndOrTimeType();
    }

    /**
     * Create an instance of {@link LanguageParamType }
     * 
     */
    public LanguageParamType createLanguageParamType() {
        return new LanguageParamType();
    }

    /**
     * Create an instance of {@link PrefParamType }
     * 
     */
    public PrefParamType createPrefParamType() {
        return new PrefParamType();
    }

    /**
     * Create an instance of {@link TimestampPropertyType }
     * 
     */
    public TimestampPropertyType createTimestampPropertyType() {
        return new TimestampPropertyType();
    }

    /**
     * Create an instance of {@link AdrPropertyType }
     * 
     */
    public AdrPropertyType createAdrPropertyType() {
        return new AdrPropertyType();
    }

    /**
     * Create an instance of {@link LangPropertyType }
     * 
     */
    public LangPropertyType createLangPropertyType() {
        return new LangPropertyType();
    }

    /**
     * Create an instance of {@link BdayPropertyType }
     * 
     */
    public BdayPropertyType createBdayPropertyType() {
        return new BdayPropertyType();
    }

    /**
     * Create an instance of {@link NamePropertyType }
     * 
     */
    public NamePropertyType createNamePropertyType() {
        return new NamePropertyType();
    }

    /**
     * Create an instance of {@link PidParamType }
     * 
     */
    public PidParamType createPidParamType() {
        return new PidParamType();
    }

    /**
     * Create an instance of {@link VcardType }
     * 
     */
    public VcardType createVcardType() {
        return new VcardType();
    }

    /**
     * Create an instance of {@link ArrayOfVcards }
     * 
     */
    public ArrayOfVcards createArrayOfVcards() {
        return new ArrayOfVcards();
    }

    /**
     * Create an instance of {@link TextListParamType }
     * 
     */
    public TextListParamType createTextListParamType() {
        return new TextListParamType();
    }

    /**
     * Create an instance of {@link TzParamType }
     * 
     */
    public TzParamType createTzParamType() {
        return new TzParamType();
    }

    /**
     * Create an instance of {@link GroupType }
     * 
     */
    public GroupType createGroupType() {
        return new GroupType();
    }

    /**
     * Create an instance of {@link ArrayOfProperties }
     * 
     */
    public ArrayOfProperties createArrayOfProperties() {
        return new ArrayOfProperties();
    }

    /**
     * Create an instance of {@link ArrayOfParameters }
     * 
     */
    public ArrayOfParameters createArrayOfParameters() {
        return new ArrayOfParameters();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PrefParamType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:ietf:params:xml:ns:vcard-4.0", name = "pref", substitutionHeadNamespace = "urn:ietf:params:xml:ns:vcard-4.0", substitutionHeadName = "baseParameter")
    public JAXBElement<PrefParamType> createPref(PrefParamType value) {
        return new JAXBElement<PrefParamType>(_Pref_QNAME, PrefParamType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LanguageParamType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:ietf:params:xml:ns:vcard-4.0", name = "language", substitutionHeadNamespace = "urn:ietf:params:xml:ns:vcard-4.0", substitutionHeadName = "baseParameter")
    public JAXBElement<LanguageParamType> createLanguage(LanguageParamType value) {
        return new JAXBElement<LanguageParamType>(_Language_QNAME, LanguageParamType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UriPropertyType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:ietf:params:xml:ns:vcard-4.0", name = "caladruri", substitutionHeadNamespace = "urn:ietf:params:xml:ns:vcard-4.0", substitutionHeadName = "baseProperty")
    public JAXBElement<UriPropertyType> createCaladruri(UriPropertyType value) {
        return new JAXBElement<UriPropertyType>(_Caladruri_QNAME, UriPropertyType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UriPropertyType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:ietf:params:xml:ns:vcard-4.0", name = "sound", substitutionHeadNamespace = "urn:ietf:params:xml:ns:vcard-4.0", substitutionHeadName = "baseProperty")
    public JAXBElement<UriPropertyType> createSound(UriPropertyType value) {
        return new JAXBElement<UriPropertyType>(_Sound_QNAME, UriPropertyType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TextPropertyType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:ietf:params:xml:ns:vcard-4.0", name = "email", substitutionHeadNamespace = "urn:ietf:params:xml:ns:vcard-4.0", substitutionHeadName = "baseProperty")
    public JAXBElement<TextPropertyType> createEmail(TextPropertyType value) {
        return new JAXBElement<TextPropertyType>(_Email_QNAME, TextPropertyType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DateAndOrTimeType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:ietf:params:xml:ns:vcard-4.0", name = "date-and-or-time")
    public JAXBElement<DateAndOrTimeType> createDateAndOrTime(DateAndOrTimeType value) {
        return new JAXBElement<DateAndOrTimeType>(_DateAndOrTime_QNAME, DateAndOrTimeType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ClientPidmapPropertyType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:ietf:params:xml:ns:vcard-4.0", name = "clientpidmap", substitutionHeadNamespace = "urn:ietf:params:xml:ns:vcard-4.0", substitutionHeadName = "baseProperty")
    public JAXBElement<ClientPidmapPropertyType> createClientpidmap(ClientPidmapPropertyType value) {
        return new JAXBElement<ClientPidmapPropertyType>(_Clientpidmap_QNAME, ClientPidmapPropertyType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UriPropertyType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:ietf:params:xml:ns:vcard-4.0", name = "url", substitutionHeadNamespace = "urn:ietf:params:xml:ns:vcard-4.0", substitutionHeadName = "baseProperty")
    public JAXBElement<UriPropertyType> createUrl(UriPropertyType value) {
        return new JAXBElement<UriPropertyType>(_Url_QNAME, UriPropertyType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:ietf:params:xml:ns:vcard-4.0", name = "uri")
    public JAXBElement<String> createUri(String value) {
        return new JAXBElement<String>(_Uri_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TextParamType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:ietf:params:xml:ns:vcard-4.0", name = "label", substitutionHeadNamespace = "urn:ietf:params:xml:ns:vcard-4.0", substitutionHeadName = "baseParameter")
    public JAXBElement<TextParamType> createLabel(TextParamType value) {
        return new JAXBElement<TextParamType>(_Label_QNAME, TextParamType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TextListPropertyType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:ietf:params:xml:ns:vcard-4.0", name = "nickname", substitutionHeadNamespace = "urn:ietf:params:xml:ns:vcard-4.0", substitutionHeadName = "baseProperty")
    public JAXBElement<TextListPropertyType> createNickname(TextListPropertyType value) {
        return new JAXBElement<TextListPropertyType>(_Nickname_QNAME, TextListPropertyType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:ietf:params:xml:ns:vcard-4.0", name = "language-tag")
    public JAXBElement<String> createLanguageTag(String value) {
        return new JAXBElement<String>(_LanguageTag_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:ietf:params:xml:ns:vcard-4.0", name = "text")
    public JAXBElement<String> createText(String value) {
        return new JAXBElement<String>(_Text_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UriPropertyType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:ietf:params:xml:ns:vcard-4.0", name = "geo", substitutionHeadNamespace = "urn:ietf:params:xml:ns:vcard-4.0", substitutionHeadName = "baseProperty")
    public JAXBElement<UriPropertyType> createGeo(UriPropertyType value) {
        return new JAXBElement<UriPropertyType>(_Geo_QNAME, UriPropertyType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TextUriPropertyType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:ietf:params:xml:ns:vcard-4.0", name = "key", substitutionHeadNamespace = "urn:ietf:params:xml:ns:vcard-4.0", substitutionHeadName = "baseProperty")
    public JAXBElement<TextUriPropertyType> createKey(TextUriPropertyType value) {
        return new JAXBElement<TextUriPropertyType>(_Key_QNAME, TextUriPropertyType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TextPropertyType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:ietf:params:xml:ns:vcard-4.0", name = "fn", substitutionHeadNamespace = "urn:ietf:params:xml:ns:vcard-4.0", substitutionHeadName = "baseProperty")
    public JAXBElement<TextPropertyType> createFn(TextPropertyType value) {
        return new JAXBElement<TextPropertyType>(_Fn_QNAME, TextPropertyType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:ietf:params:xml:ns:vcard-4.0", name = "boolean")
    public JAXBElement<Boolean> createBoolean(Boolean value) {
        return new JAXBElement<Boolean>(_Boolean_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TextPropertyType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:ietf:params:xml:ns:vcard-4.0", name = "role", substitutionHeadNamespace = "urn:ietf:params:xml:ns:vcard-4.0", substitutionHeadName = "baseProperty")
    public JAXBElement<TextPropertyType> createRole(TextPropertyType value) {
        return new JAXBElement<TextPropertyType>(_Role_QNAME, TextPropertyType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TextPropertyType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:ietf:params:xml:ns:vcard-4.0", name = "gender", substitutionHeadNamespace = "urn:ietf:params:xml:ns:vcard-4.0", substitutionHeadName = "baseProperty")
    public JAXBElement<TextPropertyType> createGender(TextPropertyType value) {
        return new JAXBElement<TextPropertyType>(_Gender_QNAME, TextPropertyType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UriPropertyType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:ietf:params:xml:ns:vcard-4.0", name = "caluri", substitutionHeadNamespace = "urn:ietf:params:xml:ns:vcard-4.0", substitutionHeadName = "baseProperty")
    public JAXBElement<UriPropertyType> createCaluri(UriPropertyType value) {
        return new JAXBElement<UriPropertyType>(_Caluri_QNAME, UriPropertyType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:ietf:params:xml:ns:vcard-4.0", name = "time")
    public JAXBElement<String> createTime(String value) {
        return new JAXBElement<String>(_Time_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UriPropertyType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:ietf:params:xml:ns:vcard-4.0", name = "fburl", substitutionHeadNamespace = "urn:ietf:params:xml:ns:vcard-4.0", substitutionHeadName = "baseProperty")
    public JAXBElement<UriPropertyType> createFburl(UriPropertyType value) {
        return new JAXBElement<UriPropertyType>(_Fburl_QNAME, UriPropertyType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TextUriPropertyType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:ietf:params:xml:ns:vcard-4.0", name = "related", substitutionHeadNamespace = "urn:ietf:params:xml:ns:vcard-4.0", substitutionHeadName = "baseProperty")
    public JAXBElement<TextUriPropertyType> createRelated(TextUriPropertyType value) {
        return new JAXBElement<TextUriPropertyType>(_Related_QNAME, TextUriPropertyType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TextParamType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:ietf:params:xml:ns:vcard-4.0", name = "type", substitutionHeadNamespace = "urn:ietf:params:xml:ns:vcard-4.0", substitutionHeadName = "baseParameter")
    public JAXBElement<TextParamType> createType(TextParamType value) {
        return new JAXBElement<TextParamType>(_Type_QNAME, TextParamType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Float }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:ietf:params:xml:ns:vcard-4.0", name = "float")
    public JAXBElement<Float> createFloat(Float value) {
        return new JAXBElement<Float>(_Float_QNAME, Float.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TextPropertyType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:ietf:params:xml:ns:vcard-4.0", name = "prodid", substitutionHeadNamespace = "urn:ietf:params:xml:ns:vcard-4.0", substitutionHeadName = "baseProperty")
    public JAXBElement<TextPropertyType> createProdid(TextPropertyType value) {
        return new JAXBElement<TextPropertyType>(_Prodid_QNAME, TextPropertyType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TextUriPropertyType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:ietf:params:xml:ns:vcard-4.0", name = "tel", substitutionHeadNamespace = "urn:ietf:params:xml:ns:vcard-4.0", substitutionHeadName = "baseProperty")
    public JAXBElement<TextUriPropertyType> createTel(TextUriPropertyType value) {
        return new JAXBElement<TextUriPropertyType>(_Tel_QNAME, TextUriPropertyType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BasePropertyType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:ietf:params:xml:ns:vcard-4.0", name = "baseProperty")
    public JAXBElement<BasePropertyType> createBaseProperty(BasePropertyType value) {
        return new JAXBElement<BasePropertyType>(_BaseProperty_QNAME, BasePropertyType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UriParamType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:ietf:params:xml:ns:vcard-4.0", name = "geoloc", substitutionHeadNamespace = "urn:ietf:params:xml:ns:vcard-4.0", substitutionHeadName = "baseParameter")
    public JAXBElement<UriParamType> createGeoloc(UriParamType value) {
        return new JAXBElement<UriParamType>(_Geoloc_QNAME, UriParamType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UriPropertyType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:ietf:params:xml:ns:vcard-4.0", name = "uid", substitutionHeadNamespace = "urn:ietf:params:xml:ns:vcard-4.0", substitutionHeadName = "baseProperty")
    public JAXBElement<UriPropertyType> createUid(UriPropertyType value) {
        return new JAXBElement<UriPropertyType>(_Uid_QNAME, UriPropertyType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TzParamType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:ietf:params:xml:ns:vcard-4.0", name = "tzid", substitutionHeadNamespace = "urn:ietf:params:xml:ns:vcard-4.0", substitutionHeadName = "baseParameter")
    public JAXBElement<TzParamType> createTzid(TzParamType value) {
        return new JAXBElement<TzParamType>(_Tzid_QNAME, TzParamType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BaseParameterType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:ietf:params:xml:ns:vcard-4.0", name = "baseParameter")
    public JAXBElement<BaseParameterType> createBaseParameter(BaseParameterType value) {
        return new JAXBElement<BaseParameterType>(_BaseParameter_QNAME, BaseParameterType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TextListPropertyType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:ietf:params:xml:ns:vcard-4.0", name = "categories", substitutionHeadNamespace = "urn:ietf:params:xml:ns:vcard-4.0", substitutionHeadName = "baseProperty")
    public JAXBElement<TextListPropertyType> createCategories(TextListPropertyType value) {
        return new JAXBElement<TextListPropertyType>(_Categories_QNAME, TextListPropertyType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UriPropertyType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:ietf:params:xml:ns:vcard-4.0", name = "source", substitutionHeadNamespace = "urn:ietf:params:xml:ns:vcard-4.0", substitutionHeadName = "baseProperty")
    public JAXBElement<UriPropertyType> createSource(UriPropertyType value) {
        return new JAXBElement<UriPropertyType>(_Source_QNAME, UriPropertyType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TextParamType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:ietf:params:xml:ns:vcard-4.0", name = "altid", substitutionHeadNamespace = "urn:ietf:params:xml:ns:vcard-4.0", substitutionHeadName = "baseParameter")
    public JAXBElement<TextParamType> createAltid(TextParamType value) {
        return new JAXBElement<TextParamType>(_Altid_QNAME, TextParamType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TextListParamType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:ietf:params:xml:ns:vcard-4.0", name = "sort-as", substitutionHeadNamespace = "urn:ietf:params:xml:ns:vcard-4.0", substitutionHeadName = "baseParameter")
    public JAXBElement<TextListParamType> createSortAs(TextListParamType value) {
        return new JAXBElement<TextListParamType>(_SortAs_QNAME, TextListParamType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TextUriPropertyType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:ietf:params:xml:ns:vcard-4.0", name = "tz", substitutionHeadNamespace = "urn:ietf:params:xml:ns:vcard-4.0", substitutionHeadName = "baseProperty")
    public JAXBElement<TextUriPropertyType> createTz(TextUriPropertyType value) {
        return new JAXBElement<TextUriPropertyType>(_Tz_QNAME, TextUriPropertyType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ArrayOfVcards }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:ietf:params:xml:ns:vcard-4.0", name = "vcards")
    public JAXBElement<ArrayOfVcards> createVcards(ArrayOfVcards value) {
        return new JAXBElement<ArrayOfVcards>(_Vcards_QNAME, ArrayOfVcards.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link VcardType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:ietf:params:xml:ns:vcard-4.0", name = "vcard")
    public JAXBElement<VcardType> createVcard(VcardType value) {
        return new JAXBElement<VcardType>(_Vcard_QNAME, VcardType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UriPropertyType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:ietf:params:xml:ns:vcard-4.0", name = "photo", substitutionHeadNamespace = "urn:ietf:params:xml:ns:vcard-4.0", substitutionHeadName = "baseProperty")
    public JAXBElement<UriPropertyType> createPhoto(UriPropertyType value) {
        return new JAXBElement<UriPropertyType>(_Photo_QNAME, UriPropertyType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PidParamType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:ietf:params:xml:ns:vcard-4.0", name = "pid", substitutionHeadNamespace = "urn:ietf:params:xml:ns:vcard-4.0", substitutionHeadName = "baseParameter")
    public JAXBElement<PidParamType> createPid(PidParamType value) {
        return new JAXBElement<PidParamType>(_Pid_QNAME, PidParamType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NamePropertyType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:ietf:params:xml:ns:vcard-4.0", name = "n", substitutionHeadNamespace = "urn:ietf:params:xml:ns:vcard-4.0", substitutionHeadName = "baseProperty")
    public JAXBElement<NamePropertyType> createN(NamePropertyType value) {
        return new JAXBElement<NamePropertyType>(_N_QNAME, NamePropertyType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:ietf:params:xml:ns:vcard-4.0", name = "integer")
    public JAXBElement<BigInteger> createInteger(BigInteger value) {
        return new JAXBElement<BigInteger>(_Integer_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BdayPropertyType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:ietf:params:xml:ns:vcard-4.0", name = "anniversary", substitutionHeadNamespace = "urn:ietf:params:xml:ns:vcard-4.0", substitutionHeadName = "baseProperty")
    public JAXBElement<BdayPropertyType> createAnniversary(BdayPropertyType value) {
        return new JAXBElement<BdayPropertyType>(_Anniversary_QNAME, BdayPropertyType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UriPropertyType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:ietf:params:xml:ns:vcard-4.0", name = "impp", substitutionHeadNamespace = "urn:ietf:params:xml:ns:vcard-4.0", substitutionHeadName = "baseProperty")
    public JAXBElement<UriPropertyType> createImpp(UriPropertyType value) {
        return new JAXBElement<UriPropertyType>(_Impp_QNAME, UriPropertyType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UriPropertyType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:ietf:params:xml:ns:vcard-4.0", name = "member", substitutionHeadNamespace = "urn:ietf:params:xml:ns:vcard-4.0", substitutionHeadName = "baseProperty")
    public JAXBElement<UriPropertyType> createMember(UriPropertyType value) {
        return new JAXBElement<UriPropertyType>(_Member_QNAME, UriPropertyType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UriPropertyType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:ietf:params:xml:ns:vcard-4.0", name = "logo", substitutionHeadNamespace = "urn:ietf:params:xml:ns:vcard-4.0", substitutionHeadName = "baseProperty")
    public JAXBElement<UriPropertyType> createLogo(UriPropertyType value) {
        return new JAXBElement<UriPropertyType>(_Logo_QNAME, UriPropertyType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TextPropertyType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:ietf:params:xml:ns:vcard-4.0", name = "note", substitutionHeadNamespace = "urn:ietf:params:xml:ns:vcard-4.0", substitutionHeadName = "baseProperty")
    public JAXBElement<TextPropertyType> createNote(TextPropertyType value) {
        return new JAXBElement<TextPropertyType>(_Note_QNAME, TextPropertyType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:ietf:params:xml:ns:vcard-4.0", name = "pid-val")
    public JAXBElement<String> createPidVal(String value) {
        return new JAXBElement<String>(_PidVal_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TextPropertyType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:ietf:params:xml:ns:vcard-4.0", name = "title", substitutionHeadNamespace = "urn:ietf:params:xml:ns:vcard-4.0", substitutionHeadName = "baseProperty")
    public JAXBElement<TextPropertyType> createTitle(TextPropertyType value) {
        return new JAXBElement<TextPropertyType>(_Title_QNAME, TextPropertyType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BdayPropertyType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:ietf:params:xml:ns:vcard-4.0", name = "bday", substitutionHeadNamespace = "urn:ietf:params:xml:ns:vcard-4.0", substitutionHeadName = "baseProperty")
    public JAXBElement<BdayPropertyType> createBday(BdayPropertyType value) {
        return new JAXBElement<BdayPropertyType>(_Bday_QNAME, BdayPropertyType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:ietf:params:xml:ns:vcard-4.0", name = "timestamp")
    public JAXBElement<String> createTimestamp(String value) {
        return new JAXBElement<String>(_Timestamp_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TextPropertyType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:ietf:params:xml:ns:vcard-4.0", name = "kind", substitutionHeadNamespace = "urn:ietf:params:xml:ns:vcard-4.0", substitutionHeadName = "baseProperty")
    public JAXBElement<TextPropertyType> createKind(TextPropertyType value) {
        return new JAXBElement<TextPropertyType>(_Kind_QNAME, TextPropertyType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:ietf:params:xml:ns:vcard-4.0", name = "date")
    public JAXBElement<String> createDate(String value) {
        return new JAXBElement<String>(_Date_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TextListPropertyType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:ietf:params:xml:ns:vcard-4.0", name = "org", substitutionHeadNamespace = "urn:ietf:params:xml:ns:vcard-4.0", substitutionHeadName = "baseProperty")
    public JAXBElement<TextListPropertyType> createOrg(TextListPropertyType value) {
        return new JAXBElement<TextListPropertyType>(_Org_QNAME, TextListPropertyType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TextParamType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:ietf:params:xml:ns:vcard-4.0", name = "calscale", substitutionHeadNamespace = "urn:ietf:params:xml:ns:vcard-4.0", substitutionHeadName = "baseParameter")
    public JAXBElement<TextParamType> createCalscale(TextParamType value) {
        return new JAXBElement<TextParamType>(_Calscale_QNAME, TextParamType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LangPropertyType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:ietf:params:xml:ns:vcard-4.0", name = "lang", substitutionHeadNamespace = "urn:ietf:params:xml:ns:vcard-4.0", substitutionHeadName = "baseProperty")
    public JAXBElement<LangPropertyType> createLang(LangPropertyType value) {
        return new JAXBElement<LangPropertyType>(_Lang_QNAME, LangPropertyType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:ietf:params:xml:ns:vcard-4.0", name = "date-time")
    public JAXBElement<String> createDateTime(String value) {
        return new JAXBElement<String>(_DateTime_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TimestampPropertyType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:ietf:params:xml:ns:vcard-4.0", name = "rev", substitutionHeadNamespace = "urn:ietf:params:xml:ns:vcard-4.0", substitutionHeadName = "baseProperty")
    public JAXBElement<TimestampPropertyType> createRev(TimestampPropertyType value) {
        return new JAXBElement<TimestampPropertyType>(_Rev_QNAME, TimestampPropertyType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AdrPropertyType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:ietf:params:xml:ns:vcard-4.0", name = "adr", substitutionHeadNamespace = "urn:ietf:params:xml:ns:vcard-4.0", substitutionHeadName = "baseProperty")
    public JAXBElement<AdrPropertyType> createAdr(AdrPropertyType value) {
        return new JAXBElement<AdrPropertyType>(_Adr_QNAME, AdrPropertyType.class, null, value);
    }

}
